### ISSUE TITLE
Python components installation

### ISSUE THREAD

**Issue by almartinflorido** [RoboticsURJC/JdeRobot#106]
Add the python components to the cmake installation process. The components will be installed in /usr/local/share/jderobot/python , then a symbolic link will be created in /usr/local/bin.

This process also will check dependencies of python component (python modules) installed in the system. For this purpose the appropriate CMakeLists.txt will be added in Deps/.

**Comment by andresjhe** [comment]
I found this, I don't know if you have already resolved this, but maybe it can help:

https://www.preney.ca/paul/archives/107
