### ISSUE TITLE
CMake error when processing introrob_py

### ISSUE THREAD

**Issue by hustcalm** [RoboticsURJC/JdeRobot#124]
Hi all,

The new commit [Fix #106 - Python components installation](https://github.com/RoboticsURJC/JdeRobot/commit/37c574a1d0072c243ded9dd5ce6382ed8be3ef15) seems to bring troubles when running `cmake .`, the outputs on my machine(Ubuntu 14.04 LTS) are as follows:

![cmake_error-introrob_py](https://cloud.githubusercontent.com/assets/1515226/7981272/70bdca76-0ae0-11e5-82b2-0168f99b1e8c.png)

What could be wrong?

Lihang

**Comment by chanfr** [comment]
I can't reproduce the problem but can you try to remove the ${} on each variable?

I mean changing:
${ICE_PY_MODULES} AND ${NUMPY_MODULES} AND ${OpenCV_PY_MODULES} AND ${QT4_PY_MODULES} AND ${QWT5_PY_MODULES}

to

ICE_PY_MODULES AND NUMPY_MODULES AND OpenCV_PY_MODULES AND QT4_PY_MODULES AND QWT5_PY_MODULES

**Comment by hustcalm** [comment]
Yeah it works!!! @chanfr  Could this issue be related with the cmake version? I'm using `2.8.12.2`.

![cmakelists txt-without-](https://cloud.githubusercontent.com/assets/1515226/7982600/2c981ae4-0aeb-11e5-9a86-5a1ffe2cc626.png)

![cmake-ok-remove-](https://cloud.githubusercontent.com/assets/1515226/7982605/342b3d7c-0aeb-11e5-939b-6d87f86c168f.png)

**Comment by chanfr** [comment]
Great! 
yes maybe the problem is the cmake version but anywayt it is better to check variables with dependencies without the ${} as we are checking the definition of the variable not its content. 

Can you send a pull request with the solution?

thanks!

**Comment by hustcalm** [comment]
Sure, see #125 . @chanfr
