### ISSUE TITLE
CMake Error: source directory plugins/refereeplugin does not contain a CMakeLists.txt file

### ISSUE THREAD

**Issue by hustcalm** [RoboticsURJC/JdeRobot#146]
![cmake_error-refereeplugin-no_cmakelists txt](https://cloud.githubusercontent.com/assets/1515226/8101363/eb5b2112-1048-11e5-9695-f7d72b5a05a0.png)

**Comment by jmplaza** [comment]
uhm... that plugin for the referee of the drone contest is not needed anymore, should be deleted from the source tree.

**Comment by fqez** [comment]
That plugin is not in the source code anymore. Please download the lastest version.
You should not have the refereeplugin in gazeboserver/plugins/

Regards.

**Comment by rocapal** [comment]
Right, it's a cmake cache problem. Just clean your workspace or download the lastest version in a clean workspace, as fqez suggested you.

**Comment by hustcalm** [comment]
Thanks for all the answers, my bad.

A `rm -rf CMakeCache.txt` will do the trick, then `cmake .` will perform normally.
