### ISSUE TITLE
Python interfaces are not installed correctly

### ISSUE THREAD

**Issue by rocapal** [RoboticsURJC/JdeRobot#161]
The __init__.py file installed under /usr/lib/python2.7/jderobot is not the correct one.  It should be install the file located in './src/stable/interfaces/python/jderobot/jderobot/__init__.py" but somehow the final file installed is "./src/stable/interfaces/python/jderobot/RoboCompJointMotor/__init__.py"

The issue is when you try to import jderobot libraries in python, it is not working due to __init__.py file does not import the correct modules.

**Comment by fqez** [comment]
Hi Roberto,

it happened to me time ago, but I fixed it (pull request #143). Is your root CMakeLists.txt updated? :S

Regards,
Fran.

**Comment by varhub** [comment]
closeable
