### ISSUE TITLE
3D teleoperator component for flyingkinect plugin

### ISSUE THREAD

**Issue by jmplaza** [RoboticsURJC/JdeRobot#164]
A new component is needed to move the flying kinect inside Gazebo-5 at will, in 3D. This will allow that sensor to move along the 3D space at the same time it provides its RGBD-data. It should provide its orders through the 3Dpose interface. The chance to accept not only instantaneous orders from the human user (through GUI), but also files with predefined 3D paths should be explored too.

**Comment by fqez** [comment]
Oh I completely forgot to open this issue, sorry! I am working on it atm, but I am having some core dumped related issues. As soon as I have the component working I'll make a pull request. Sorry again!
