### ISSUE TITLE
pose3D interface supersedes encoders interface in all components

### ISSUE THREAD

**Issue by jmplaza** [RoboticsURJC/JdeRobot#165]
Encoders interface represents a 2D position: x,y,theta. Now a more general interface (pose3D) will be used for 2D positions and 3D positions. Pose3D includes XYZH for position and a Quaternion for orientation.

**Comment by fqez** [comment]
Pull request #170, the pioneer was merged some days ago in the pull request #153

**Comment by jmplaza** [comment]
In Gazebo: Pioneer, Kobuki and Formula1 now only provide pose3D interfaces. But Kobuki driver still provides encoders ICE interface.

**Comment by fqez** [comment]
Now all our robots support pose3D only!
