### ISSUE TITLE
Add GPS support to ardrone_server

### ISSUE THREAD

**Issue by varhub** [RoboticsURJC/JdeRobot#191]
*As part of my TFM, I will add GPS support to ardrone_server.
These lines are a brief introduction for future job and pull request*

# Add GPS support to ardrone_server
**Up to date info is here:**
https://jderobot.org/Varribas-tfm/ARDrone:GPS_Support

## Preliminary description
ARDrone 2.0 have GPS support via **Flight Recorder** [1]. (alternative: uBlox [2])

There is an experimental support  in AutonomyLab (because there is not updated sdk). See:
* http://answers.ros.org/question/127996/is-it-possible-to-get-gps-data-from-ardrone-with-flight-recorder-in-ardrone_autonomy
* AutonomyLab/ardrone_autonomy/issues/90
* AutonomyLab/ardronelib/commit/ebf2e656d91dca4c0b84f233f29e3b283619f35e
* AutonomyLab/ardrone_autonomy/commit/a986b3380da8d9306407e2ebfe7e0f2cd5f97683
* felixge/node-ar-drone/issues/75
* felixge/node-ar-drone/issues/94

Some info:
* GPS format has changed since 2.4.8 firmware.
* Functional GPS may requires connection with a official client (like Android AR.FreeFlight)
 Fast GPS Fix position requires a file with predicted Satellites position. This file takes next flow:
 * 1. AR.FreeFlight downloads prediction from Parrot servers (internet required).
 * 2. File is send from mobile to ArDrone
 * 3. File is send from ArDrone to Flight Recorder
 This initial setup could require up to 30 minutes (from expected 24 sec).

[1] http://ardrone2.parrot.com/apps/flight-recorder/
[2] https://wiki.paparazziuav.org/wiki/AR_Drone_2/GPS

**Comment by fqez** [comment]
Merged!
