### ISSUE TITLE
ArDrone's **roll** is inverted

### ISSUE THREAD

**Issue by varhub** [RoboticsURJC/JdeRobot#192]
ARDrone's **roll** seems to be inverted.
Issue affects to real and simulated robot.

* Simulated robot test:
![ardrone_inverse_roll](https://cloud.githubusercontent.com/assets/5702557/10391709/fc13f470-6e80-11e5-94bd-6f4c2987b7a5.png)

* Real robot:
[video](http://jderobot.org/store/varribas/uploads/videos/tfm-ardrone_server.webm) from min 1:20 to 1:40

**Affected components**: introrob_py
**JdeRobot version**: github 834a1168895fd1f760eb604449c2453f7b0ee6a3 "#168 Included functionality to get a single image from jderobotViewer render"

PS: [unfetch changes from upstream](https://github.com/RoboticsURJC/JdeRobot/compare/834a1168895fd1f760eb604449c2453f7b0ee6a3...master) and [my changes to introrob_py](https://github.com/RoboticsURJC/JdeRobot/compare/834a1168895fd1f760eb604449c2453f7b0ee6a3...varhub:introrob_py-sandbox)

**Comment by varhub** [comment]
Also roll control in inverted, so sign seems consistent.

Perhaps solution is switch sign in single line of code, but it can also be exposing a bug, like a different unpack or operation with an array due a numpy upgrade (for example).

Waiting for any kind of confirmation.

**Comment by almartinflorido** [comment]
Hi varhub,

the pull request #197 modified the sign of roll.

**Comment by varhub** [comment]
Hi @almartinflorido, just a question.
I did a minor refactor of Pose3D interface and notice that only roll is positive.
It is due a rotation of reference system or for quadrotor plugin compatibility?
https://github.com/varhub/JdeRobot/blob/d8c9c2b779ed8d63e99225052f8f109540bc3df1/src/stable/components/ardrone_server/src/components/pose3di.cpp#L69
Thanks in advance.

**Comment by fqez** [comment]
Hi,
I've tested this same issue in a real ArDrone with introrob_py and both roll and yaw are inverted as well.

**Comment by varhub** [comment]
added to #229 changeset
