### ISSUE TITLE
Introrob_py: improve interaction with real-Ar.Drone

### ISSUE THREAD

**Issue by almartinflorido** [RoboticsURJC/JdeRobot#196]
Introrob currently has a limited control over the real-ARDrone. Is necessary add improvements to better control of the quadrotor.

**Comment by varhub** [comment]
Component roughly tested with under develop ardrone_server and gazebo. Working without problems.
Include patches from:
* #182 "Fix Python/Numpy future warning for `img != None`"
* AutonomyLab/ardrone_autonomy/pull/160 "Zero cmd_vel on takeoff, reset, and land"
