### ISSUE TITLE
Inclusion in the third party repository (and packages) of Parrot SDK for their drones

### ISSUE THREAD

**Issue by jmplaza** [RoboticsURJC/JdeRobot#198]
Our driver for ArDrones from Parrot (ArDrone1 and ArDrone2) wraps the Parrot SDK. We have done some modifications on the original SDK to work for us. This modified Parrot SDK should be included in our "Third party software", and a debian package should be generated for it. Our JdeRobot package should depend on this package.

**Comment by fqez** [comment]
Yes, everything is ready for testing the SDK package now. This week the debian package will be uploaded to an apt repository to make it installable from command line.There is some information [here](http://jderobot.org/Varribas-tfm/ARDrone:cmake_advanced) about the manual installation of the SDK. The installation from packages will be posted there when the package has been tested.

**Comment by varhub** [comment]
Task moved to RoboticsURJC/JdeRobot-ThirdParty/pull/1

**Comment by varhub** [comment]
To finalize this issue, I managed ardronelib dependency through pkg-config.
Pull request at RoboticsURJC/JdeRobot-ThirdParty#3

It also includes a ffmpeg-0.8.pc to allow linking to this library (even from plain g++).

Adapted JdeRobot version at #203

I tested both and works like a charm. @fpez, could you test it?

---

PS: also a minor improvement at RoboticsURJC/JdeRobot-ThirdParty#2
For me, merge these three issues will conclude this one.

**Comment by fqez** [comment]
Merged, thanks!
