### ISSUE TITLE
Missing the configuration files (.cfg) of turtlebot plugin with the new debian packages

### ISSUE THREAD

**Issue by almartinflorido** [RoboticsURJC/JdeRobot#220]
Hi all,

yesterday I installed on a virtual machine (x64) the latests debian packages and the configuration files of turtlebot (cam_sensor_left.cfg, turtlebot_laser.cfg, etc.) plugins doesn't appear in the default directory (/usr/local/share/jderobot/gazebo/plugins/turtlebot).

regards

**Comment by fqez** [comment]
Hi Alberto, they are all in the /usr/local/share/jderobot/conf

**Comment by almartinflorido** [comment]
Ok, Francisco but for pioneer/flyingball/kinect/nao/quadrotor plugin the files they are in /usr/local/share/jderobot/gazebo/plugins/<plugin>, no? 
Maybe I copied this files and I don't remember.

thanks

**Comment by fqez** [comment]
Yes, you are right. I modified the turtlebot plugin some time ago, and I decided not to copy the .cfg files again, I think it makes no sense to have them duplicated. I will tell JoseMaria if we can remove .cfg files of the others plugins directories, or we keep the .cfg files also in the plugin folder instead.

**Comment by almartinflorido** [comment]
Ok @fqez  thanks
