### ISSUE TITLE
The kinect mesh don't appear in turtlebot model

### ISSUE THREAD

**Issue by almartinflorido** [RoboticsURJC/JdeRobot#221]
Hi all,

in ardrone-turtlebot.world the path to kinect mesh is commented and it is incorrect, the result is that the kinect mesh don't appear in the turtlebot model
![turtlebot_without_kinect](https://cloud.githubusercontent.com/assets/12018634/11019879/b5207fb2-860d-11e5-95e1-00ee876e12a7.png)

The correct path is //kinect/meshes/kinect.dae instead of of //kinectJde/meshes/kinect.dae

![turtlebot_with_kinect](https://cloud.githubusercontent.com/assets/12018634/11019898/183c8942-860e-11e5-8632-cf4731cfdae1.png)

regards

**Comment by fqez** [comment]
Hi Alberto, thank you for reporting this. The current world ardrone-turtlebot is not correct. It redefines the existent turtlebot model (which should be at ~/.gazebo/models. I'm goingo to update the world to solve this issue. 

Regards!

**Comment by almartinflorido** [comment]
Thanks @fqez

**Comment by fqez** [comment]
You can test it now, if you want! pull request #226

**Comment by almartinflorido** [comment]
Thans @fqez  maybe later I can test it
