### ISSUE TITLE
Task: libeasyiceconfig

### ISSUE THREAD

**Issue by varhub** [RoboticsURJC/JdeRobot#240]
# A library to tame Ice.Config

Refer to: http://jderobot.org/Varribas-tfm/libiceconfigresolver
*development state: proposal*

**Comment by varhub** [comment]
## Update
C++ and Python implementation:
- https://github.com/jderobot-varribas/libeasyiceconfig/releases/tag/0.9
- https://github.com/jderobot-varribas/pyeasyiceconfig/releases/tag/0.9.1

**Comment by jmplaza** [comment]
Solved
