### ISSUE TITLE
[Proposal] Increment automatically package version each time that it is built

### ISSUE THREAD

**Issue by varhub** [RoboticsURJC/JdeRobot#268]
# Increment automatically package version each time that it is built

Create script that fetch current version from apt-get and perform a `version++`. If new package pass all test it can be pushed to repository. Therefore, all users are notified about new version even it implies a minor fix.

With this approach, version maintenance is outsourced, so git do not need to absorb it.

***Though for release candidates only.*** Use cases:
  a. If at-get report a x.y.z-rcN, then package will be x.y.z-rc${N+1}
  b. if apt-get report x.y.z, but is ancient than hardcored at CPack, use that one and append an `-rc1`
  c. if (b) but reverse, three options:
    i. do nothing
    ii. assert with an error/warning due incompatibility
    iii. try to recover last RC for this x.y.z
  (iii) provides a useful use case for real projects but do not worth here: ability to patch previous releases

(a) is the normal case, (b) ensures compatibility with major/minor/patch upgrade. Therefore, git saves x.y.z and allow tagging, but is isolated from repo maintenance.

Eventually, debian package will contain which commit was HEAD at built time. So anyone can trace back build process and do it by itself (with a simple apt-cache show or dpkg --info)

PS: same thing but with a stable + dev branches with hotfix will be the real world use of this proposal.

**Comment by fqez** [comment]
It would be very useful. We also need to create a tag of JdeRobot for each new package uploaded to the APT repository in order to maintain the consistency between the source code and the current package available. The more automatic task we have, the more time we save.
