### ISSUE TITLE
new KobukiViewer for web browser component

### ISSUE THREAD

**Issue by aitormf** [RoboticsURJC/JdeRobot#293]
A multiplatform component is needed for teleoperating Kobuki and Pioneer wheeled robots and viewing their onboard sensors.

I thought that to do so is a good idea to use a web page as all actuall device (PC, tablet, mobile, ...) have browser.

**Comment by varhub** [comment]
*Related to #289*

Could you deal with this?
The best way will be a lateral panel listing each "front end" and adding it to current context by click on it.
Therefore this "main view" can handle every robot ;)
What do you think?

**Comment by aitormf** [comment]
I'm doing a version in my TFG: http://jderobot.org/Aitormf-tfg#Greatest_Hits
