### ISSUE TITLE
Support for kinect2 device (K4W2)

### ISSUE THREAD

**Issue by chanfr** [RoboticsURJC/JdeRobot#3]
A server component is needed to serve the depth and color information of this new device. This information will be given using the standard cameras interface.

**Comment by hustcalm** [comment]
@chanfr 
Any idea that how can I help with this feature development?

I suppose that we need a driver for K4W2, then designs the wrapper API to serve the depth and color frame?

**Comment by chanfr** [comment]
Uploaded kinect2Server component. See readme.md inside the component directory for more details.
