### ISSUE TITLE
new Gazebo plugin with a Formula1 car

### ISSUE THREAD

**Issue by jmplaza** [RoboticsURJC/JdeRobot#308]
to be used in TeachingRobotics and other applications. It should include a frontal camera and support the motors ICE interface for car movements. Right now we have a regular car (http://jderobot.org/Andresjhe-tfg#Car_Teleoperator)

**Comment by fqez** [comment]
Done! sorry for the delay.... again. The model is ready in the PR #350. Tested with introrob_qt. See the PR description for further information.

**Comment by fqez** [comment]
Merged!
