### ISSUE TITLE
sample configuration file for cameraserver should not use ServiceName by default

### ISSUE THREAD

**Issue by jmplaza** [RoboticsURJC/JdeRobot#309]
because it prevents the simple use without starting the sevice name. It should work stand alone, as in the manual web page (http://jderobot.org/index.php/Running_JdeRobot#Cameraserver_.2B_Cameraview)

**Comment by jmplaza** [comment]
In addition I had to change CameraSrv.Camera.0.Uri to 0 in my computer as @02081994 suggested

**Comment by fqez** [comment]
Merged!
