### ISSUE TITLE
Python module jderobot incomplete with new release of JdeRobot

### ISSUE THREAD

**Issue by almartinflorido** [RoboticsURJC/JdeRobot#312]
Hi all,

this morning I install the new release of JdeRobot in a clean virtual machine with Ubuntu 14.04 Gnome x86.

I detect that the python module for JdeRobot is incomplete, threse are the actual components (extracted from ```/usr/lib/python2.7/jderobot/__init__.py```):

joinmotor_ice

And these are the components for old JdeRobot version:

bodymovements_ice
naomotions_ice
genericData_ice
laser_ice
body_ice
remoteCloud_ice
pose3d_ice
pose3dmotors_ice
encoders_ice
ptmotors_ice
replayControl_ice
ptencoders_ice
varcolor_ice
jcm_ice
exceptions_ice
motors_ice
remoteConfig_ice
namingService_ice
bodyencoders_ice
pose3dencoders_ice
common_ice
naofollowball_ice
datetime_ice
cmdvel_ice
image_ice
kinectleds_ice
wiimote_ice
pointcloud_ice
camera_ice
containers_ice
sonars_ice
ardroneextra_ice
recorder_ice
navdata_ice
bodymotors_ice

does anyone can confirm?

regards

**Comment by fqez** [comment]
I thought this was solved at #143. But I will take a look again.
