### ISSUE TITLE
The ventral camera of Ar.Drone doesn't see the turtleboot stickers in virtualized environment

### ISSUE THREAD

**Issue by almartinflorido** [RoboticsURJC/JdeRobot#315]
Hi,

In a clean installation of JdeRobot in a virtual machine (x86) the ventral camera of Ar.Drone doesn't see the turtlebot stickers.

![turtlebot_no_colors](https://cloud.githubusercontent.com/assets/12018634/12560982/ef78acca-c39d-11e5-857e-65b335a0a55d.png)

regards

**Comment by fqez** [comment]
This is a render problem that Gazebo has on virtual machines, I guess. You can see how Gazebo renders the scene in the following image:

![gazebo_render_bug](https://cloud.githubusercontent.com/assets/8070644/12568939/69e83cc4-c3ca-11e5-9da3-725eb6f66d86.png)

As you can see, the car is hidden by the floor, so a similar problem occurs with the tag. Honestly I have no solution for this issue unless you use a native ubuntu&gazebo installation.
