### ISSUE TITLE
Example of cameraserver+cameraview revisited, libEasyIceConfig

### ISSUE THREAD

**Issue by jmplaza** [RoboticsURJC/JdeRobot#329]
Yesterday, the example of cameraserver+cameraview (directions to launch it are here http://jderobot.org/index.php/Running_JdeRobot#Cameraserver_.2B_Cameraview ) didn't work for two students. It failed to locate cameraserver.cfg, cameraviewer.cfg and cameraviewer.glade files.

The files are already installed by the jderobot package at the corresponding directories but they are not found when running the components from other directories. libEasyIceConfig was designed to solve this topic, searching for this glade and configuration files at certain directories. Some more testing on this is needed.

**Comment by fqez** [comment]
This doesn't work because the current pacakage was generated before merging the easyice and resourcelocator integration in each jderobot component. The next package will solve this issue :)
It should work now if the source code is compiled!

**Comment by fqez** [comment]
Fixed with the new package v5.3.1-rc4

**Comment by jmplaza** [comment]
It works like a charm with the new release, just following the instructions in the manual as they are. Good job!
