### ISSUE TITLE
example KobukiDriver + KobukiViewer

### ISSUE THREAD

**Issue by jmplaza** [RoboticsURJC/JdeRobot#336]
Current state of this example is 'almost done'. Works fine for simulated Kobuki, but the movement in the real Kobuki robot suddenly stops after 2 seconds (approx) after moving forward.

Simple instructions to run this example, both simulated and real would be helpful at http://jderobot.org/index.php/Running_JdeRobot#Wheeled_robots

**Comment by fqez** [comment]
Done [here](http://jderobot.org/Running_JdeRobot#Real_Kobuki_.2B_Kobuki_driver_.2B_KobukiViewer). It only need the video.
