### ISSUE TITLE
Create new GreenArdrone2 for the drone contest

### ISSUE THREAD

**Issue by almartinflorido** [RoboticsURJC/JdeRobot#361]

**Comment by almartinflorido** [comment]
![green_ardrone](https://cloud.githubusercontent.com/assets/12018634/13553536/30f0e01e-e38d-11e5-992b-ea02cfce06b8.png)

![dronecampeones](https://cloud.githubusercontent.com/assets/12018634/13553537/34d6600a-e38d-11e5-94a5-e4d0a0982461.png)

**Comment by fqez** [comment]
Merged at #362
