### ISSUE TITLE
Change UavViewerJS GUI

### ISSUE THREAD

**Issue by aitormf** [RoboticsURJC/JdeRobot#398]
I think that UavViewerJS GUI  is impractical for teleoperate drones from mobile devices. It should be able to use each control with a finger and not having to surf the website.

It should be more like this app:

![image](https://cloud.githubusercontent.com/assets/16046048/14103701/a3133f9a-f5a1-11e5-86c8-16cbac39cda3.png)

**Comment by fqez** [comment]
merged!
