### ISSUE TITLE
New world for Gazebo

### ISSUE THREAD

**Issue by mazafrav** [RoboticsURJC/JdeRobot#399]
I think it would be useful adding a world which i have been working on. It's for drone testing in interior spaces and it is based on the world 'GrannysFlat' where i added a drone model and some AprilTags spreaded over the flat's walls.

![flatwiki2](https://cloud.githubusercontent.com/assets/12997270/14175744/64a0a7fe-f74d-11e5-8b76-e6236444b931.png)

**Comment by fqez** [comment]
Merged! Thanks!
