### ISSUE TITLE
Incorret name for 3DViewer

### ISSUE THREAD

**Issue by almartinflorido** [RoboticsURJC/JdeRobot#401]
Hi all,

the CMakeLists.txt for 3DViewer contain the old name of the component (jdeViewer) see [1]:

regards

[1]: https://github.com/RoboticsURJC/JdeRobot/blob/master/src/stable/components/3DViewer/CMakeLists.txt

**Comment by chanfr** [comment]
I don't know why some of the changes have not been included into the pull request. 
I fixed it.

Thanks!
