### ISSUE TITLE
An update of Gazebo crash the gazebo setup

### ISSUE THREAD

**Issue by almartinflorido** [RoboticsURJC/JdeRobot#406]
Hi all,

recently Gazebo launched a new version (5.3), when you install the new version the gazebo components of JdeRobot doesn't work because the paths are changed. Maybe #405  can resolve the problem.

I trying to reproduce this error in a new clean installation.

regards

**Comment by almartinflorido** [comment]
The solution purpose by @varhub #405 fix this problem, please merge it.

**Comment by fqez** [comment]
Fixed dependency lookup too at 32ebc73352e3e9729e900d99bf650685b6938a73 Now it requires gazebo 5.3.0 instead of gazebo 5.1.0
