### ISSUE TITLE
Error compiling ardrone_server

### ISSUE THREAD

**Issue by samartin** [RoboticsURJC/JdeRobot#432]
If the whole jderobot package is compilated having installed just jderobot-deps-dev, when the compilation is in ardrone_server, an error stops the compilation. @jmplaza told me that this is because ardronelib is needed to compile it. The error should not happen though.

**Comment by fqez** [comment]
Hi, if you want to compile the ardrone_server driver, you must first compile ardronelib from: https://github.com/RoboticsURJC/JdeRobot-ThirdParty/tree/master/ardronelib
