### ISSUE TITLE
CMAKE_CXX_FLAGS  resetting within components without need.

### ISSUE THREAD

**Issue by lr-morales** [RoboticsURJC/JdeRobot#435]
Some parts of JdeRobot still reset `CMAKE_CXX_FLAGS` inside their CMakeLists.txt without really needing it. Note that I'm talking about reset as in

`set( CMAKE_CXX_FLAGS "-Wno-deprecated")`

and not appending as in

`set( CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-deprecated")`

This behabiour prevents the usage of external flags given at generation time and inhibits the variable population done in the root CMakeLists.txt

Affected components I found are:
- ardrone_server
- cameraview
- followBall
- naoviewer
- openni1Server
- openniServer
- recorder
- recorder2
- remoteConfiguration
- replayController
- replayer
- replayer2
- rgbdViewer
- teleoperator

Affected gazebo plugins I found are:
- f1
- kinect
- flyingKinect
- turtlebot

I suppose that some of these are remnants from the time before restructuring the cmake generation chain and others are there because they are based in the previous ones.
Could someone confirm that this behaviour isn't intended or clarify why is intended?

**Comment by fqez** [comment]
Merged!
