### ISSUE TITLE
[tools] uavviewer GUI should be reduced

### ISSUE THREAD

**Issue by jmplaza** [RoboticsURJC/JdeRobot#442]
in order to be usable in small screens. Instead of having all graphical widgets in the same single window, always, it is better to unfold several subwindows at will. In a checkbox the user can choose to launch additional subwindows to show sensors, or whatever. These subwindows will be smaller than the single all-widgets-there window, like in the design of the current GUI of kobukiviewer tool.

**Comment by fqez** [comment]
Having some troubles with this issue, core dumps about the widgets created around the main window. Working on solving this ASAP.
