### ISSUE TITLE
Missing Actors_GrannyAnnie2.world

### ISSUE THREAD

**Issue by aitormf** [RoboticsURJC/JdeRobot#448]
I was running [JdeRobot expamples](http://jderobot.org/index.php/Running_JdeRobot) and when I was trying run [FlyingKinect example](http://jderobot.org/index.php/Running_JdeRobot#Simulated_FlyingKinect_.2B_NavigatorCamera_.2B_RGBDViewer), gazebo did't found **Actors_GrannyAnnie2.world**.

I've looked in the repository and can not find the world in the worlds directory of gazeboserver

**Comment by jmplaza** [comment]
You can find it at https://github.com/Javii91/Domotic repository. Please include it in the directory src/stable/drivers/gazeboserver/worlds of the official source code through a PullRequest.

**Comment by fqez** [comment]
merged! thanks
