### ISSUE TITLE
Deps CMakeLists for openGL: deprecated variable usage and wrong output

### ISSUE THREAD

**Issue by lr-morales** [RoboticsURJC/JdeRobot#452]
The CMakeLists file for checking and setting include and link directories globally for openGL makes use of the variable `GLUT_LIBRARY`, which is described inside CMake's FindGLUT.cmake as 
> deprecated setting for backwards compatibility with CMake1.4
The variable `GLUT_LIBRARIES` should be used instead i whole file.

Also, when one of all GLUT-related libraries (Xmu, Xi...) is missing, the following happens:
-  `link_directories` tries to populate without proper cleaning or checking from our side, making cmake to think that the missing library is instead a relative path. For example:
 
>   CMake Warning (dev) at Deps/opengl/CMakeLists.txt:6 (link_directories):
>    This command specifies the relative path
>
>      GLUT_Xmu_LIBRARY-NOTFOUND
>
>    as a link directory.
>
>    Policy CMP0015 is not set: link_directories() treats paths relative to the
>    source dir.  Run "cmake --help-policy CMP0015" for policy details.  Use the
>    cmake_policy command to set the policy and suppress this warning.
>    Call Stack (most recent call first):
>    Deps/LoadJderobotDependencies.cmake:12 (include)
>    CMakeLists.txt:117 (include)
>  This warning is for project developers.  Use -Wno-dev to suppress it.

- JdeRobot CMakeLists reports the library "as found" under a list of paths with a `NOTFOUND` variable inside; for example:

>  OpenGL libraries found at /usr/lib/i386-linux-gnu/libglut.so;GLUT_Xmu_LIBRARY-NOTFOUND;/usr/lib/i386-linux-gnu/libXi.so

If all related libraries are needed in JdeRobot base, I suggest - at least - to check first the list for `NOTFOUND` before trying to link the paths.

**Comment by fqez** [comment]
Just merged, thanks!
