### ISSUE TITLE
Recorder and Replayer GUIs don't load in Linux package

### ISSUE THREAD

**Issue by aitormf** [RoboticsURJC/JdeRobot#458]
I try run recorder with Linux package installation and it shows ths error:

<pre>Create consumer 
Create consumer 
Loading glade 
 
 
(recorder:3695): libglade-WARNING **: could not find glade file './recordergui.glade' 
terminate called after throwing an instance of 'Gnome::Glade::XmlError' 
Abortado (core generado) </pre>

I've seen it is because when loading the file .glade does:
`refXml = Gnome::Glade::Xml::create("./recordergui.glade"); `

Instead of (like cameraview):

<pre>const std::string gladepath = resourcelocator::findGladeFile("recordergui.glade"); 
… 
…
 refXml = Gnome::Glade::Xml::create(gladepath);</pre>

**Comment by aitormf** [comment]
Also I've seen replayer has the same problem

**Comment by fqez** [comment]
Hi! yes, recorder and replayer seems not to have the resource locator feature implemented, also recorder2 and replayer2 lack tihs functionality. It's easy to solve though.

**Comment by fqez** [comment]
Thanks! merged
