### ISSUE TITLE
VisualHFSM: should be possible to choose the proxy name

### ISSUE THREAD

**Issue by reysam93** [RoboticsURJC/JdeRobot#459]
When editing the .cfg file for ICE with VisualHFSM, should be possible to choose the proxy name, understanding for this name:
automata.ArDroneExtra.Proxy=[proxyName]:default -h localhost -p 9000

**Comment by fqez** [comment]
Merged, is #462 the same issue?

**Comment by reysam93** [comment]
No, they are different issues.
