### ISSUE TITLE
Bad format of description and summary for the JdeRobot package

### ISSUE THREAD

**Issue by lr-morales** [RoboticsURJC/JdeRobot#465]
Trying to install a fresh generated jderobot package reports this error:

````
dpkg: error processing archive jderobot_5.3.2_i386.deb (--install):
 parsing file '/var/lib/dpkg/tmp.ci/control' near line 9 package 'jderobot':
 field name `The' must be followed by colon
````
Checking the control file of the package reveals that the long description doesn't meet the standard of leaving a blank at the beginning of each line ([Section "5.6.13 Description"]( https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-Description)  of Debian Policy Manual).
Related to closed issue #407.

**Comment by fqez** [comment]
Merged!
