### ISSUE TITLE
Problem with Actors_GrannyAnnie2.world with FlyingKinect

### ISSUE THREAD

**Issue by aitormf** [RoboticsURJC/JdeRobot#470]
Error with the kinect flying configuration files of Actors_GrannyAnnie2.world, Gazebo looking for ones that are not:

<pre>
$ gazebo Actors_GrannyAnnie2.world 
PropertiesI.cpp:PropertiesI.cpp:407: Ice::FileException: 
file exception: 407: Ice::FileException: 
file exception: No such file or directory 
path: kinectPose3d.cfg 
No such file or directory 
path: kinectPose3d.cfg 
ObjectAdapterI.cpp:939: Ice::InitializationException: 
initialization exception: 
object adapter `Kinect' requires configuration 
ObjectAdapterI.cpp:939: Ice::InitializationException: 
initialization exception: 
object adapter `Kinect' requires configuration
</pre>

**Comment by fqez** [comment]
I think resourcelocator is not implemented in flyingkinect plugin, so I supose you need to run this world from a directory where flyingkinect .cfg's files are (typically /usr/local/share/jderobot/conf or /usr/local/share/jderobot/gazebo/plugins/flyingKinect) till resource locator is included.
