### ISSUE TITLE
[tools] basic_component.py, an application template for robot behaviors in Python

### ISSUE THREAD

**Issue by jmplaza** [RoboticsURJC/JdeRobot#477]
We have a basic_component in C++, which is a simple template for robot behaviors in C++. A component example in Python is needed. It connects to at least two ICE interfaces, one for motors and another one for camera images. It has (1) a communication side, (2) a GUI side and (3) a behavior side. The behavior side runs in iterations and includes a perceptive part and a control part.

It is aimed to be the simple skeleton for robot applications in Python.

**Comment by fqez** [comment]
Merged, thanks!
