### ISSUE TITLE
[drivers] MAVLinkServer for MAVLink based drones

### ISSUE THREAD

**Issue by jmplaza** [RoboticsURJC/JdeRobot#479]
Several drones use the PixHawk autopilot board, and such board (and others) follow the MAVLink protocol (Micro Aerial Vehicle communication protocol, from Lorenz Meier http://qgroundcontrol.org/mavlink/start). Support in JdeRobot to this type of drones is desirable http://jderobot.org/J.canoma-tfg#MAVLinkServer

**Comment by fqez** [comment]
Merged the first MAVLinkServer version.
