### ISSUE TITLE
review the GUI of all glade based tools

### ISSUE THREAD

**Issue by aitormf** [RoboticsURJC/JdeRobot#481]
We would have to review the GUI of the glade based tools because to basic_component the same thing happens that recorder and replayer (#458): The don't locate glade file because in the code we use a path instead of resourcelocator

- [x] opencvdemo
- [x] replayer2
- [x] naoviewer
- [x] basic_component
- [x] recorder2
- [x] rgbdManualCalibrator
- [x] cameraview
- [x] navigatorCamera
- [x] rgbdCalibrator
- [x] rgbdViewer
- [x] giraffeClient
- [x] replayController
- [x] visualHFSM

**Comment by fqez** [comment]
Not every tool has the resourcelocator feature coded sadly. I did include it in some tools (PR #304) but yes, we should include it in every glade based tool.

**Comment by aitormf** [comment]
you're right, I'm going to add a list of all the tools that have interface glade to know which must check

**Comment by fqez** [comment]
List updated based on this commit: https://github.com/RoboticsURJC/JdeRobot/pull/304/commits/e6b99ddad2a0be1b3f97f2c70d11319352a6ab33
