### ISSUE TITLE
opencvdemo component runtime error

### ISSUE THREAD

**Issue by abhi-kumar** [RoboticsURJC/JdeRobot#54]
While running the opencvdemo component I get the following errors - 
"
Loading glade
Network.cpp:2169: Ice::ConnectionRefusedException:
connection refused: Connection refused
"

Please help me cope with the issue.

Regards,
Abhishek

**Comment by gsssrao** [comment]
Could you tell the contents of opencvdemo.cfg and cameraserver.cfg? In cameraserver.cfg are the endpoints this:
CameraSrv.Endpoints=default -h 0.0.0.0 -p 9999 
Also is the opencvdemo.cfg like this:
Opencvdemo.Camera.Proxy=cameraA:tcp -h 0.0.0.0 -p 9999

**Comment by abhi-kumar** [comment]
cameraserver.cfg has "CameraSrv.Endpoints=default -h 0.0.0.0 -p 9999"

and opencvdemo.cfg has "Opencvdemo.Camera.Proxy=cameraA:tcp -h 127.0.0.1 -p 9998"

**Comment by gsssrao** [comment]
Aah! That's the cause of the error. cameraserver is listening for client calls on port 9999 and opencvdemo is sending the call to port 9998. Change 9998 to 9999 and try.

**Comment by abhi-kumar** [comment]
Sir, I changed the port setting as instructed and run the command " ./opencvdemo --Ice.Config=opencvdemo.cfg" but I still get the same error.

**Comment by gsssrao** [comment]
Have you started the cameraserver. You need to first start the cameraserver and then when it is running, start opencvdemo on a different terminal.

PS: I am also a student. So you can drop the "Sir".

**Comment by abhi-kumar** [comment]
Thanks a lot with that, I was assuming the fact that killing the terminal would still keep the server running as I recently studied about ICE and it has that option. We can implement that option I guess. Thanks for the valuable input from your side.

**Comment by gsssrao** [comment]
You're welcome.
