### ISSUE TITLE
Installation of quadrotor plugins

### ISSUE THREAD

**Issue by fqez** [RoboticsURJC/JdeRobot#73]
Hi,

there is a problem with the installation of the new quadrotor plugins, they are not installed in its own directory after typing *sudo make install* . In fact they are not installed anywhere.
Maybe those installation directives are missing in the CMakeLists file of the gazeboserver component.

**Comment by chanfr** [comment]
Can you check if the this problem persists?
 I've made some changes in the pluing installation process (#77)

**Comment by fqez** [comment]
Everything is alright now.

Thanks!
