### ISSUE TITLE
Referee refactoring

### ISSUE THREAD

**Issue by andresjhe** [RoboticsURJC/JdeRobot#85]
Hi!

Since there's a plugin for Gazebo in charge of measuring distances and a python program that ask for those and creates a graph, it would be a great idea to fuse both in one. 

That's the purpose of this issue. As soon as I finish I will pull request so we can add it to our components.

**Comment by jmplaza** [comment]
With the new refactorization of referee, it does not require any special plugin running on gazebo. It is only a viewer, written in python, that connects to the plugins of both drones, the cat and the mouse.
