### ISSUE TITLE
New release of introrob.py 

### ISSUE THREAD

**Issue by jmplaza** [RoboticsURJC/JdeRobot#92]
Old release of introrob.py doesn't work after changing the image ICE interface. 

In addition, new improvements should be added in order to use it in the new drone programming course, like to work even without connection to CMDvel ICE interface, or ardrone-extra ICE. This will allow to connect introrob.py with a cameraserver to test the image processing from video files, for instance.

**Comment by jmplaza** [comment]
Its integration in the JdeRobot building chain is also tricky. We should take into account the questions you commented in the mailing list about it, Alberto, introducing in CMake the dependencies of debian packages which contain required python modules for introrob.py (better than using PIP).

**Comment by almartinflorido** [comment]
Uploaded in the pull request #98 , for the CMake chain I will create a new issue
